security:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:8080,http://localhost:3000,http://localhost:4200}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.eveonline.com