name: PR Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21  # Change version if needed
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use 'zulu' or 'adopt' if needed
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn clean install